param([string]$GameDirectory)
$ErrorActionPreference = 'Stop'
$log = Join-Path (Split-Path $PSScriptRoot -Parent) 'launcher.log'
Start-Transcript -Path $log -Force | Out-Null
try {
$root = Split-Path $PSScriptRoot -Parent
. "$PSScriptRoot/ensure-java.ps1"
Initialize-Left4CraftJava -Root $root
if (!$GameDirectory) {
    if (!(Test-Path -LiteralPath "$root/settings.json")) { throw 'Run Setup.cmd first.' }
    $GameDirectory = (Get-Content -LiteralPath "$root/settings.json" -Raw | ConvertFrom-Json).GameDirectory
}
$exe = Join-Path $GameDirectory 'left4dead.exe'
if (!(Test-Path -LiteralPath $exe)) { throw 'The selected L4D1 folder no longer exists. Run Setup.cmd again.' }
if (Get-Process left4dead -ErrorAction SilentlyContinue) { throw 'Close the existing L4D1 session first.' }
if (!(Test-Path -LiteralPath (Join-Path $GameDirectory 'left4dead/addons/left4craft.dll'))) { throw 'Run Setup.cmd first.' }
$instance = "$root/Minecraft/Prism/instances/Left4Craft/instance.cfg"
$text = [IO.File]::ReadAllText($instance)
$text = [regex]::Replace($text, '(?m)^JvmArgs=.*$', 'JvmArgs=--enable-native-access=ALL-UNNAMED -Dskycraft.startHidden=false -Dskycraft.showWindow=true -Dskycraft.link=Local\\Left4Craft_v1')
[IO.File]::WriteAllText($instance, $text)
Set-Left4CraftIniValues -Path $instance -Values @{ ShowConsole = 'true'; ShowConsoleOnError = 'true' }
$dll = Join-Path $GameDirectory 'left4dead/addons/left4craft.dll'
$expectedDll = Get-Content -LiteralPath "$root/bin/left4craft-sha256.txt" -Raw
if ((Get-FileHash -LiteralPath $dll -Algorithm SHA256).Hash -ne $expectedDll.Trim()) { throw 'The installed DLL is incomplete or differs from this package. Run Repair-Startup.cmd.' }
$pluginPath = ([IO.Path]::GetFullPath($dll)).Replace('\', '/')
# Source's startup command construction strips quotes from +command arguments.
# Its console tokenizer treats colon as a separator, so an unquoted D:/... becomes D.
# Keep the quoted DLL path inside an exec config instead of putting it in +plugin_load.
$cfgDirectory = Join-Path $GameDirectory 'left4dead/cfg'
New-Item -ItemType Directory -Force -Path $cfgDirectory | Out-Null
$bootCfg = Join-Path $cfgDirectory 'left4craft_boot.cfg'
$bootLines = @(
    '// Generated by Left4Craft Launch.cmd; used only by +exec left4craft_boot.'
    'echo "[Left4Craft] Loading the verified plugin..."'
    ('plugin_load "' + $pluginPath + '"')
    'plugin_print'
    'mat_queue_mode 0'
    'echo "[Left4Craft] Synchronous world rendering enabled."'
)
[IO.File]::WriteAllText($bootCfg, (($bootLines -join "`r`n") + "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
$arguments = '-steam -insecure -novid -console -condebug +sv_lan 1 +exec left4craft_boot +map l4d_hospital01_apartment singleplayer'
Write-Host "Plugin loading config: $bootCfg"
$startedAt = Get-Date
Write-Host "Plugin file verified: $pluginPath"
Write-Host "Game launch arguments: $arguments"
Write-Host 'Starting offline single player. F8 requests Minecraft control; allow time for collision streaming. F9 returns native control.'
Write-Host 'Steam Offline Mode is optional for this launcher; use it if you want Steam itself disconnected.'
$gameProcess = Start-Process -PassThru -FilePath $exe -WorkingDirectory $GameDirectory -ArgumentList $arguments
# Prism supports --offline NAME after account validation and first-time downloads.
$minecraftLauncher = Start-Process -PassThru -FilePath "$root/Minecraft/Prism/prismlauncher.exe" -WorkingDirectory "$root/Minecraft/Prism" -ArgumentList '--dir . --launch Left4Craft --offline Left4Craft'

Write-Host "L4D1 launch requested (process $($gameProcess.Id))."
Write-Host "Minecraft launcher started (process $($minecraftLauncher.Id)); the Minecraft window and game log are now visible for startup testing."
Write-Host 'Allow Minecraft to finish starting. Focus L4D1, close its console and press F8 only after the bridge loads.'
Write-Host 'Checking the native plugin startup log (up to 45 seconds)...'
$pluginLogs = @((Join-Path $GameDirectory 'left4craft.log'), (Join-Path $GameDirectory 'left4dead/left4craft.log'))
$foundLog = $false
for ($attempt = 0; $attempt -lt 45; $attempt++) {
    foreach ($path in $pluginLogs) {
        if (Test-Path -LiteralPath $path) {
            $item = Get-Item -LiteralPath $path
            if ($item.LastWriteTime -ge $startedAt.AddSeconds(-1)) {
                Write-Host "Native plugin log: $path"
                Get-Content -LiteralPath $path -Tail 12 | ForEach-Object { Write-Host $_ }
                $foundLog = $true
                break
            }
        }
    }
    if ($foundLog) { break }
    Start-Sleep -Seconds 1
}
if (!$foundLog) {
    Write-Host 'No fresh native plugin log was found. The DLL may not have loaded.' -ForegroundColor Yellow
    $console = Join-Path $GameDirectory 'left4dead/console.log'
    if (Test-Path -LiteralPath $console) {
        Write-Host "Relevant game console messages: $console"
        Get-Content -LiteralPath $console -Tail 400 | Select-String -Pattern 'plugin|left4craft|insecure|failed|error' | ForEach-Object { Write-Host $_ }
    }
    Write-Host 'In the L4D console, run the following to show the exact loader error:'
    Write-Host 'exec left4craft_boot'
    Write-Host 'The config also prints the plugin list; its plugin_load line preserves the quoted path.'
}
$running = Get-CimInstance Win32_Process -Filter "Name='left4dead.exe'" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($running -and $running.CommandLine -and $running.CommandLine -notmatch '(?i)(?:^|\s)-insecure(?:\s|$)') {
    Write-Host 'The running game command line does not contain -insecure; the bridge will refuse to load. Steam may have restarted the game without these arguments.' -ForegroundColor Yellow
}
Write-Host "This window can be closed. Startup messages are saved to $log"
} catch {
    Write-Host "Launch failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Startup log: $log"
    exit 1
} finally {
    Stop-Transcript | Out-Null
}
